[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5432/:splat"
  status = 200

[[redirects]]
  from = "/video_feed"
  to = "http://localhost:5432/video_feed"
  status = 200