[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/video_feed"
  to = "/.netlify/functions/app"
  status = 200